### ISSUE TITLE
v. 1.0.0.12 will not launch

### ISSUE THREAD

**Issue by sootysax** [CourseplayPathEditor/CoursePlay-Editor-6#1]
I cannot get v. 1.0.0.12 to open on my computer.   Trying to start the program just spins my cursor, and then stops.  Nothing ever launches.  Same with V 1.00.11

I went back and tried v. 1.0.0.2 again, and that opens.. but will not load Marwell Manor Farm.  

Not sure if there is any kind of log I can post to see why the app crashes on launch.
My settings.xml is set correctly.   
[settings.zip](https://github.com/CourseplayPathEditor/CoursePlay-Editor-6/files/2890069/settings.zip)

**Comment by alpha117** [comment]
Yep, 1.0.0.12 fixes the 'WP height issues', I had the same issue with 1.0.0.2 could not open ANY courses. 

Anything in the windows event viewer?

**Comment by sootysax** [comment]
From Win 10 Reliability Monitor:

Source
FS19_FarmingDesktop

Summary
Stopped working

Date
‎2/‎21/‎2019 11:24 AM

Status
Report sent

Description
Faulting Application Path:	C:\Program Files\FS19_FarmingDesktop\FS19_FarmingDesktop.exe

Problem signature
Problem Event Name:	CLR20r3
Problem Signature 01:	FS19_FarmingDesktop.exe
Problem Signature 02:	1.0.0.1
Problem Signature 03:	5c6c845b
Problem Signature 04:	mscorlib
Problem Signature 05:	4.7.3324.0
Problem Signature 06:	5c09b1b7
Problem Signature 07:	1687
Problem Signature 08:	fd
Problem Signature 09:	System.InvalidOperationException
OS Version:	10.0.17134.2.0.0.768.101
Locale ID:	1033
Additional Information 1:	cd7b
Additional Information 2:	cd7bf8628ab760ee9171d2b4f5c6ef4b
Additional Information 3:	8f44
Additional Information 4:	8f445fcb8fb5538df3b075685ff4cf64

Extra information about the problem
Bucket ID:	57e3eee9dbc2da0488fd3b8130441360 (1800660852064654176)

**Comment by alpha117** [comment]
[FS19_Marwell_Manor_Farm.ModMap.zip](https://github.com/CourseplayPathEditor/CoursePlay-Editor-6/files/2890145/FS19_Marwell_Manor_Farm.ModMap.zip)

Try these ones in 1.0.0.2

**Comment by sootysax** [comment]
I can't load any Marwell courses in 1.0.0.2

**Comment by PromGames** [comment]
Just quick question, @sootysax you have Windows 10. .?

Did you try to take down the antivirus, maybe that's the problem, I can't get properly signed the program

**Comment by PromGames** [comment]
I will produce a version 14 signing in different way to see if that is the problem. In 1 hour I expect will be in drive. You are getting from there right?

**Comment by PromGames** [comment]
I will produce a version 14 signing in different way to see if that is the problem. In 1 hour I expect will be in drive. You are getting from there right?

**Comment by PromGames** [comment]
Version 14 in google drive, please try that version to see if we are lucky and you get it working

**Comment by alpha117** [comment]
#14 OK here

**Comment by sootysax** [comment]
this is really frustrating... i dont know why it wont open for me..  

I turned off any active protection from Acronis or Windows Defender.  Yes Windows 10 Home, latest update

v,14

Source
FS19_FarmingDesktop

Summary
Stopped working

Date
‎2/‎21/‎2019 2:56 PM

Status
Report sent

Description
Faulting Application Path:	C:\Program Files\FS19_FarmingDesktop\FS19_FarmingDesktop.exe

Problem signature
Problem Event Name:	CLR20r3
Problem Signature 01:	FS19_FarmingDesktop.exe
Problem Signature 02:	1.0.0.14
Problem Signature 03:	5c6efe67
Problem Signature 04:	mscorlib
Problem Signature 05:	4.7.3190.0
Problem Signature 06:	5b693a01
Problem Signature 07:	1684
Problem Signature 08:	fd
Problem Signature 09:	System.InvalidOperationException
OS Version:	10.0.17763.2.0.0.768.101
Locale ID:	1033
Additional Information 1:	cd7b
Additional Information 2:	cd7bf8628ab760ee9171d2b4f5c6ef4b
Additional Information 3:	b48e
Additional Information 4:	b48ef014161e22c579d856428f5d49bb

Extra information about the problem
Bucket ID:	b1246979e961998d17460ccc51551bf8 (1677041982919482360)

**Comment by PromGames** [comment]
Let's try this, although is not very clean. Just you scott.  (Alpha do not install this version)

This version is the clickonce version. Lets try it. It is in drive  Called courseplay Publish, after uncompressing the zip, run the setup. exe


Alfredo,

**Comment by alpha117** [comment]
Roger that

**Comment by sootysax** [comment]
Same thing happens

Source
FS19_FarmingDesktop

Summary
Stopped working

Date
‎2/‎21/‎2019 3:10 PM

Status
Report sent

Description
Faulting Application Path:	C:\Users\ScottM\AppData\Local\Apps\2.0\4RZBBC9D.P0P\DEGHHEVJ.76D\fs19..tion_b56fde8c02101789_0001.0000_c43ef512ae740dbd\FS19_FarmingDesktop.exe

Problem signature
Problem Event Name:	CLR20r3
Problem Signature 01:	FS19_FarmingDesktop.exe
Problem Signature 02:	1.0.0.14
Problem Signature 03:	5c6efe67
Problem Signature 04:	mscorlib
Problem Signature 05:	4.7.3324.0
Problem Signature 06:	5c09b1b7
Problem Signature 07:	1687
Problem Signature 08:	fd
Problem Signature 09:	System.InvalidOperationException
OS Version:	10.0.17763.2.0.0.768.101
Locale ID:	1033
Additional Information 1:	c017
Additional Information 2:	c017ef439d46988211470cfe9c3ee7fc
Additional Information 3:	40b6
Additional Information 4:	40b65851827022e4ed55c106c9d1a179

Extra information about the problem
Bucket ID:	453c30f592eefcccaf4e37b452051e56 (2255801710968905302)

**Comment by PromGames** [comment]
@sootysax I have uploaded another new version 14, could you try, it will ask to install vcredist

Lets cross fingers

**Comment by sootysax** [comment]
![capture](https://user-images.githubusercontent.com/6591048/53201466-1b6d0c80-35f2-11e9-8dfb-9a5924f5843d.PNG)

**Comment by sootysax** [comment]
I changed settins.xml to :  
"Setting gamexmlfile="C:\Users\ScottM\Documents\My Games\FarmingSimulator2019\"

instead of

 "Setting gamexmlfile="C:\Users\ScottM\Documents\My Games\FarmingSimulator2019\gameSettings.xml"

and it opens

**Comment by sootysax** [comment]
though I'm getting this message when trying to open Marwell savegame:

![capture2](https://user-images.githubusercontent.com/6591048/53201863-10ff4280-35f3-11e9-8653-a6d57a2f7406.PNG)

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Temp\FS19_Marwell_Manor_Farm'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path, String searchPattern)
   at Microsoft.VisualBasic.FileIO.FileSystem.FindPaths(FileOrDirectory FileOrDirectory, String directory, String wildCard)
   at Microsoft.VisualBasic.FileIO.FileSystem.FindFilesOrDirectories(FileOrDirectory FileOrDirectory, String directory, SearchOption searchType, String[] wildcards, Collection`1 Results)
   at Microsoft.VisualBasic.FileIO.FileSystem.FindFilesOrDirectories(FileOrDirectory FileOrDirectory, String directory, SearchOption searchType, String[] wildcards)
   at Microsoft.VisualBasic.MyServices.FileSystemProxy.GetFiles(String directory, SearchOption searchType, String[] wildcards)
   at FS19_FarmingDesktop.MainForm1.ComboBox2_SelectedIndexChanged(Object sender, EventArgs e)
   at System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ComboBox.WmReflectCommand(Message& m)
   at System.Windows.Forms.ComboBox.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
FS19_FarmingDesktop
    Assembly Version: 1.0.0.14
    Win32 Version: 1.0.0.14
    CodeBase: file:///C:/Program%20Files/FS19_FarmingDesktop/FS19_FarmingDesktop.exe
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 10.0.0.0
    Win32 Version: 14.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3353.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Runtime.Remoting
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Remoting/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll
----------------------------------------
DevComponents.DotNetBar2
    Assembly Version: 12.5.0.2
    Win32 Version: 12.5.0.2
    CodeBase: file:///C:/Program%20Files/FS19_FarmingDesktop/DevComponents.DotNetBar2.DLL
----------------------------------------
DevComponents.DotNetBar.Schedule
    Assembly Version: 12.5.0.2
    Win32 Version: 12.5.0.2
    CodeBase: file:///C:/Program%20Files/FS19_FarmingDesktop/DevComponents.DotNetBar.Schedule.DLL
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
Magick.NET-Q16-AnyCPU
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.0.0102
    CodeBase: file:///C:/Program%20Files/FS19_FarmingDesktop/Magick.NET-Q16-AnyCPU.DLL
----------------------------------------
ICSharpCode.SharpZipLib
    Assembly Version: 0.86.5.0
    Win32 Version: 0.86.5.0
    CodeBase: file:///C:/Program%20Files/FS19_FarmingDesktop/ICSharpCode.SharpZipLib.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by PromGames** [comment]
Did you uncompressed it? It needs to be unzipped in mod folder. The map I mean

**Comment by PromGames** [comment]
At least now you are able to run it.

**Comment by PromGames** [comment]
You also have a wrong modfolder, can you put the complete settings now

**Comment by PromGames** [comment]
You also have a wrong modfolder, can you put the complete settings now

**Comment by PromGames** [comment]
Also could be the proble in your game setting.xml,check if override is set to true and the path is to your mod folder and not to.  C:\temp

**Comment by sootysax** [comment]
[settings.zip](https://github.com/CourseplayPathEditor/CoursePlay-Editor-6/files/2891475/settings.zip)

  Setting gamexmlfile="C:\Users\ScottM\Documents\My Games\FarmingSimulator2019\" /
  Setting modrepository="C:\Users\ScottM\Documents\My Games\FarmingSimulator2019\mods\" /
  Setting gameexefile="C:\Program Files (x86)\Steam\steamapps\common\Farming Simulator 19\FarmingSimulator2019.exe" /

**Comment by PromGames** [comment]
You have to have the following data correct:
```

<Settings>
  <Setting gamexmlfile="C:\Users\ScottM\Documents\My Games\FarmingSimulator2019" />
  <Setting modrepository="C:\Users\ScottM\Documents\My Games\FarmingSimulator2019\mods" />
  <Setting gameexefile="C:\Program Files (x86)\Steam\steamapps\common\Farming Simulator 19" />
</Settings>
```

**Comment by sootysax** [comment]
ah..  that worked!!  gamesettings.xml WAS set to False, and C:\temp!

**Comment by PromGames** [comment]
Then is working ??

**Comment by sootysax** [comment]
![bam](https://user-images.githubusercontent.com/6591048/53205103-5293eb80-35fb-11e9-8a65-bad594e39b33.PNG)

**Comment by sootysax** [comment]
boom..  i dont know how my gamesettings.xml got set that way..  but maybe good to have in your documentation :)

**Comment by PromGames** [comment]
Thank you very much, you detect two important mistakes in my configuration.

1.- VCRedist was missing in your windows
2.- No routine for gamesettings set to false
