### ISSUE TITLE
Ability to select multiple Waypoints

### ISSUE THREAD

**Issue by alpha117** [CourseplayPathEditor/CoursePlay-Editor-6#11]
This would able to select multiple WPs to enable them to keep their integrity with each other.

Select either via 'Shift +click'   or a 'click and drag' bounding box around the WPs

**Comment by PromGames** [comment]
Yes, It is in the pipeline.

**Comment by alpha117** [comment]
Fantastic

**Comment by Opa-Andre** [comment]
Great idea, maybe this way it would be possible to further enhance the functionality by populating  MinSpeed and MaxSpeed setting boxes. When entering values within the boxes and setting a checkmark all selected WP with a lower speed than the MinSpeed value will be set to the MinSpeed value and all WP with a higher speed than MaxSpeed will be filled up with the maxSpeed settings.
