### ISSUE TITLE
cannot open courses from modded maps

### ISSUE THREAD

**Issue by joshvzeyl** [CourseplayPathEditor/CoursePlay-Editor-6#12]
When i want to load the course of an mod map the program doesn't open it and gives an error. i have set the source path to where my mods are. ingame maps i can open.

what am i doing wrong?

![2019-02-22 2](https://user-images.githubusercontent.com/26695249/53265976-cd363700-36df-11e9-8619-c4c47158df5c.png)
![2019-02-22 3](https://user-images.githubusercontent.com/26695249/53265977-cd363700-36df-11e9-84c9-77b32c4a9c7a.png)

**Comment by PromGames** [comment]
Yes, I Think is due to the gamesettings.xml

This will solved in next version but in the mean time you can solve this way:

SET to true directoryoverride in gamesettings.xml and set the directory like this, you have it as False
```
<modsDirectoryOverride active="True" directory="C:\Users\User\My Games\FarmingSimulator2019\mods" />
```

**Comment by PromGames** [comment]
I suppose you have got to get it running, I will close the issue then.
