### ISSUE TITLE
Changing WP speed does not save

### ISSUE THREAD

**Issue by alpha117** [CourseplayPathEditor/CoursePlay-Editor-6#13]
You can change the number, but it does not save the changes

![image](https://user-images.githubusercontent.com/30005040/53288913-949d6880-3786-11e9-887a-9230fdb3b27f.png)

Also yo note , if you 'add a course' , Wp speeds delfault to 'Zero', you cannot change these WP speeds either. Therefore currently, 'add course' does not work as it should and cannot be used.

**Comment by PromGames** [comment]
You have to leave the speed and point to other field and then is updated, I think

Alfredo Prieto

**Comment by alpha117** [comment]
Yep, make the change and then click in another field, must be a field not the map.

Works fine...thanks
