### ISSUE TITLE
Feature Request : Key Commands

### ISSUE THREAD

**Issue by sootysax** [CourseplayPathEditor/CoursePlay-Editor-6#15]
I think that in the difficulty selecting the correct waypoint when they are close together (still an issue in v.18 for me), a few key commands are needed.

1. Deselect any selected waypoints: to avoid accidentally moving a selected waypoint when trying to choose another close by waypoint

2. Next / Previous Waypoint on selected course: to make it less necessary to correctly select a tight waypoint with the mouse, a next and previous waypoint key commands would make it easy to get to the waypoint you are intending to select.

**Comment by PromGames** [comment]
IN V18 is not solved the problem, the code will come in V19 on. 

This was implemented in coursedrawer and Tiny Will transport to here

**Comment by sootysax** [comment]
ah ok.   key commands would still be nice.
