### ISSUE TITLE
v18 Crashes on Savegame Load

### ISSUE THREAD

**Issue by sootysax** [CourseplayPathEditor/CoursePlay-Editor-6#16]
![2019-02-23_16-06-01](https://user-images.githubusercontent.com/6591048/53291685-420f7c80-3785-11e9-8afc-db2cb3f7f3ea.png)

This has happened to me twice now, I'm not sure what causes it, but I have to restore my courses from a backup I made to get CP Editor to work again.  CP Editor will crash on loading the savegame.

Corrupt Courses:
https://drive.google.com/file/d/1c1EWzLzvD0ViMCN2IbjJJx0GB0MKhlU-/view?usp=sharing

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Runtime.InteropServices.ExternalException (0x80004005): A generic error occurred in GDI+.
   at System.Drawing.Graphics.MeasureString(String text, Font font, SizeF layoutArea, StringFormat stringFormat)
   at System.Drawing.Graphics.MeasureString(String text, Font font)
   at System.Windows.Forms.ListBox.UpdateMaxItemWidth(Object item, Boolean removing)
   at System.Windows.Forms.ListBox.ObjectCollection.AddInternal(Object item)
   at System.Windows.Forms.ListBox.ObjectCollection.Add(Object item)
   at System.Windows.Forms.CheckedListBox.ObjectCollection.Add(Object item, CheckState check)
   at FS19_FarmingDesktop.MainForm1.fillCourseList()
   at FS19_FarmingDesktop.MainForm1.ComboBox2_SelectedIndexChanged(Object sender, EventArgs e)
   at System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ComboBox.WmReflectCommand(Message& m)
   at System.Windows.Forms.ComboBox.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
FS19_FarmingDesktop
    Assembly Version: 1.0.0.18
    Win32 Version: 1.0.0.18
    CodeBase: file:///C:/Program%20Files/FS19_FarmingDesktop/FS19_FarmingDesktop.exe
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 10.0.0.0
    Win32 Version: 14.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3353.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Runtime.Remoting
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Remoting/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll
----------------------------------------
DevComponents.DotNetBar2
    Assembly Version: 12.5.0.2
    Win32 Version: 12.5.0.2
    CodeBase: file:///C:/Program%20Files/FS19_FarmingDesktop/DevComponents.DotNetBar2.DLL
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
Magick.NET-Q16-AnyCPU
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.0.0102
    CodeBase: file:///C:/Program%20Files/FS19_FarmingDesktop/Magick.NET-Q16-AnyCPU.DLL
----------------------------------------
ICSharpCode.SharpZipLib
    Assembly Version: 0.86.5.0
    Win32 Version: 0.86.5.0
    CodeBase: file:///C:/Program%20Files/FS19_FarmingDesktop/ICSharpCode.SharpZipLib.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by sootysax** [comment]
In these courses, I can restore the courseManager_backup.xml and it will work..   There is a 'not used' spot in slot 11.   I can add one more course, and it fills slot 11.  If I add another course and it fills Slot 47, then I will get this crash.. 

Even if I delete the course that filled that 47th slot and try and reload in CE, it still crashes

**Comment by sootysax** [comment]
I guess I had old courses 47-64 in the folder from before the last time it crashed and I restored..  I deleted those Courses 47-64 but still when trying to save a 47th course, it crashes when i load it

**Comment by sootysax** [comment]
well - i opened up the courseManager.xml in notepad++ and there were about 27000 blank lines that got in the id="3" line..   not sure how that came about.. but deleting it made things better

**Comment by PromGames** [comment]
I couldnt reproduce the proble but maybe now is solved as we review the whole routine for deleting wp and courses.

**Comment by sootysax** [comment]
It hasn't happened again for me either..  closing
