### ISSUE TITLE
Angle Value?

### ISSUE THREAD

**Issue by alpha117** [CourseplayPathEditor/CoursePlay-Editor-6#17]
What is this number in relationship to?
Also I cannot change it, should/could this be possible
![image](https://user-images.githubusercontent.com/30005040/53304423-e3253280-386c-11e9-9c22-0d9ba0f806b1.png)

**Comment by PromGames** [comment]
There was a button that recalculate angles but is hide because is not working properly, TinyCrocodile has made a good routine and he will make it available

**Comment by TinyCrocodile** [comment]
Heading direction south is 0°   and north is 180°  everything in direction right are positive Angle and direcion right are negative angle with direction west is exactly -90°. This needs some more work as the anlgle between two line segments seems to be a bit different of what courseplay calculates. Especially when driving reverse this seemed to be the case. 
Original Coursedrawer had a error when calculating the angle i will look into it and see if still the case.

**Comment by alpha117** [comment]
Many thanks, the question is, 'if' this can be changed in the editor then would this have a better effect when merging 2 courses, it looks like that CP adds a WP on the merge?

**Comment by alpha117** [comment]
After some testing on how CP merges courses and what data does it use to determine where two courses are merged. It looks like it take the angle of the 1st course crossing point and continue on that track until the track crosses course #2, then it looks for the closest crossing WP of course #2 and then makes the merge. This is the reason that merging courses are not a smooth transition as it could be. 

If you can change the WP angle of WP, then there would be a better fit, it will not be a perfectly smooth transition,but would be better than it currently is. Will also stop having to record more courses to make that smooth 'merge'. 

Also the WP angle, if possible to be the same as a compass heading (North=0, East=90 etc ), that way the user would have a better understanding of what it place in the angle box. 

Just a thought
