### ISSUE TITLE
Add New Course error and changes

### ISSUE THREAD

**Issue by alpha117** [CourseplayPathEditor/CoursePlay-Editor-6#18]
1. Add Course

![image](https://user-images.githubusercontent.com/30005040/53361946-e84bb580-3930-11e9-997f-c77e44dd9b8a.png)

2. Extend Course

3. Fill every 20m, it should add the WP's along the 'line direction'. IT does the 1st one then they are added at 90 degrees
![image](https://user-images.githubusercontent.com/30005040/53362110-598b6880-3931-11e9-8bf1-d5fcc6577e07.png)

4. Delete Course
![image](https://user-images.githubusercontent.com/30005040/53362173-aec77a00-3931-11e9-84de-a2098a62bb7d.png)

5. Add Course
![image](https://user-images.githubusercontent.com/30005040/53362223-95263280-3931-11e9-97b8-aebd76efb439.png)

**Comment by TinyCrocodile** [comment]
already in pipeline will be my next to do

**Comment by alpha117** [comment]
First class Tiny, great work

**Comment by PromGames** [comment]
I totally agree, marvellous work. 

This problem is redundant, every time we make a calculation on courseId, we add the idx for courses but we didn't really implement completely and in some old routines coming from coursedrawer keep the errors.

I love the way Tiny did in his development and I expect he will be able to transport here.

At least, we have now a stable and working version.

**Comment by PromGames** [comment]
I totally agree, marvellous work. 

This problem is redundant, every time we make a calculation on courseId, we add the idx for courses but we didn't really implement completely and in some old routines coming from coursedrawer keep the errors.

I love the way Tiny did in his development and I expect he will be able to transport here.

At least, we have now a stable and working version.

**Comment by alpha117** [comment]
Yep and it is getting better and better very quickly, first class

**Comment by alpha117** [comment]
Just had a new error, this time just added course, moved WP's around and then delete course and then got this
![image](https://user-images.githubusercontent.com/30005040/53446033-db4ec500-3a09-11e9-9b0a-0ddbb1f5ac70.png)

**Comment by PromGames** [comment]
Make the photo next time with the details screen and we can see where is thee error

**Comment by alpha117** [comment]
Here you go. Error can be reproduced.  1. Add course 2. Fill with WP 3. Move a few WP's around 4. Delete course
![image](https://user-images.githubusercontent.com/30005040/53450378-f7effa80-3a13-11e9-9a5c-29a66d1f2f5a.png)
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at FS19_FarmingDesktop.clsCourses.get_CourseList()
   at FS19_FarmingDesktop.MainForm1.fillCourseList()
   at FS19_FarmingDesktop.MainForm1.butDelCourse_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
FS19_FarmingDesktop
    Assembly Version: 1.0.0.21
    Win32 Version: 1.0.0.21
    CodeBase: file:///G:/FS19_FarmingDesktop/FS19_FarmingDesktop.exe
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 10.0.0.0
    Win32 Version: 14.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3353.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Runtime.Remoting
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Remoting/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll
----------------------------------------
DevComponents.DotNetBar2
    Assembly Version: 12.5.0.2
    Win32 Version: 12.5.0.2
    CodeBase: file:///G:/FS19_FarmingDesktop/DevComponents.DotNetBar2.DLL
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
Magick.NET-Q16-AnyCPU
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.0.0102
    CodeBase: file:///G:/FS19_FarmingDesktop/Magick.NET-Q16-AnyCPU.DLL
----------------------------------------
ICSharpCode.SharpZipLib
    Assembly Version: 0.86.5.0
    Win32 Version: 0.86.5.0
    CodeBase: file:///G:/FS19_FarmingDesktop/ICSharpCode.SharpZipLib.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by PromGames** [comment]
Yes, the error is coming in my last modification, I have to check, I think forget to set some index. I will take a look @tinycrocodile

**Comment by PromGames** [comment]
Yes, the error is coming in my last modification, I have to check, I think forget to set some index. I will take a look @tinycrocodile
