### ISSUE TITLE
Info about new Wp distance setting

### ISSUE THREAD

**Issue by TinyCrocodile** [CourseplayPathEditor/CoursePlay-Editor-6#20]
I have introduced a different way of choosing waypoint distance. 
It allows to select a given distance or also any number can be set in the textbox.

New the wp distance setting applies not only to the fill wp function but also to the wp append and wp insert function.

Wp append is inserting the new waypoint after the selected wp. If at the last wp course is extended in direction of last crs segment with wp distance setting. 

Wp insert is inserting a new waypoint bevore the selected. If at the first wp it adds a wp to the beginning of the course. Direction is the first course segment with the new wp distance setting. 

If the distance between the waypoints is smaller than the wp distance setting, then the new wp is created in the middle of the course segment.

**Comment by alpha117** [comment]
looking good as always
