### ISSUE TITLE
Question about open beta

### ISSUE THREAD

**Issue by KenStumich** [CourseplayPathEditor/CoursePlay-Editor-6#21]
since the Y-value is stored in courseplay, it is no longer possible to use an old version of a cp-editor. Therefore, I am waiting since then for a beta version of your project.
how long does it take to open beta?
Kind regards

**Comment by PromGames** [comment]
There is no open beta for the moment. Just for testing by the members of the team that provide feedback on the usage. we are fine tuning and solving issues, translating, etc... If you want to help, let me know through a pm to my GitHub profile and I will send you a welcome member link.

**Comment by PromGames** [comment]
There is no open beta for the moment. Just for testing by the members of the team that provide feedback on the usage. we are fine tuning and solving issues, translating, etc... If you want to help, let me know through a pm to my GitHub profile and I will send you a welcome member link.

**Comment by PromGames** [comment]
There is no open beta for the moment. Just for testing by the members of the team that provide feedback on the usage. we are fine tuning and solving issues, translating, etc... If you want to help, let me know through a pm to my GitHub profile and I will send you a welcome member link.

**Comment by PromGames** [comment]
There is no open beta for the moment. Just for testing by the members of the team that provide feedback on the usage. we are fine tuning and solving issues, translating, etc... If you want to help, let me know through a pm to my GitHub profile and I will send you a welcome member link.
