### ISSUE TITLE
CoursePlay 6 Editor coming soon ??

### ISSUE THREAD

**Issue by freddi1995** [CourseplayPathEditor/CoursePlay-Editor-6#22]
Its nice that someone is working on the Editor for CP6 because sometimes if u drive like 2m false u know u can drive the whole course again (sometimes deleting some points in the XML works too but its much work to set the points per XML and deleting the false ones). so i wanted to ask whenn the Editor will be released or if an alpha version could be released so u can work with courseplay in an better way.

**Comment by Messy71** [comment]
^ Any news for us plebs?
