### ISSUE TITLE
Zoom level increase

### ISSUE THREAD

**Issue by PromGames** [CourseplayPathEditor/CoursePlay-Editor-6#3]
I will modify the zoom level to allow more deep view in the map, this create two major problems,

when zoom goes over certain number, the screen starts flickering, goback one step in zoom and will stop flickering, thats the maximun it allows without flickering.

We are working to see how we can solve this problem

Next version in drive will have free zoom

Remember the two main new features:
You can manage also 16x maps, The program is ready to be tested. (PV19 Factories)
You can export courses as splines to be imported in GE.
You can also export splines and import as courses.

Prom

**Comment by PromGames** [comment]
@sootysax @alpha117 

New Version in Drive with better zoom posibilities. Ver 17

Please give me feedback.

**Comment by alpha117** [comment]
I am at zoom 800 all good, no flickering
