### ISSUE TITLE
Request: Option to view speed in MPH or KPH

### ISSUE THREAD

**Issue by sootysax** [CourseplayPathEditor/CoursePlay-Editor-6#4]
Being an American user, having the option to see speed in MPH would make my brain very happy.

**Comment by alpha117** [comment]
Agree from the UK

**Comment by PromGames** [comment]
I was thinking how to deal with this.

I know that you can choose in settings;

```
<units>
        <money>1</money>
        <miles>false</miles>
        <fahrenheit>false</fahrenheit>
        <acre>false</acre>
    </units>
```

But there is no setup in courseplay for units, and this means that if recorded speed is 15 km/h means is 10 miles per hour. then if miles is set to true, vehicle will go at 15 miles???  Is that correct?

We allow to change speed in courseplay, 
I can convert all your sppeds from miles to km or km to miles, That could be a good feature and easy to do.  But we need then some index to say if the course was recorded in miles or in km/h

But, if I do not have that index, I can get crazy results.

**Comment by Opa-Andre** [comment]
As "speed" is an universal name in the waypoint and there is no way to determine if a course was recorded in km/h or mph, I would leave it there that way. Many users also exchange map courses with other users - so its not really determinable, if the original speed values of the courses of a map match to the speed setting in the corresponding save game as there is no reference about in the course play files themself which kind of speed was used for recording. Therefore what do you think about making a "global setting" available  for the selected map/savegame with the ability after confirming a warning dialog ("do you really want?")to recalculate the speed entries of all courses of the selected map from km/h to mph or vice versa, showing a progress bar during recalculation, saving the files and inform the user about that the conversation has been done. This global setting could be named "speed conversion" or alike.
