### ISSUE TITLE
Error when moving WP's

### ISSUE THREAD

**Issue by alpha117** [CourseplayPathEditor/CoursePlay-Editor-6#5]
Happens after moving approx. 8 WP's

![image](https://user-images.githubusercontent.com/30005040/53221521-a5a08980-3661-11e9-9c09-a53420d265ff.png)

**Comment by PromGames** [comment]
@alpha117 

Can you check again if you have the same problem with version 20.

Thanks

**Comment by alpha117** [comment]
cannot replicate in #21
