### ISSUE TITLE
Version number not correct for application

### ISSUE THREAD

**Issue by alpha117** [CourseplayPathEditor/CoursePlay-Editor-6#7]
Farming Desktop is at this version

![image](https://user-images.githubusercontent.com/30005040/53229912-5f592380-367d-11e9-8264-5796ca0dbe91.png)

But Courseplay Editor can be at a different version. Currently at #17 but not correct. A very small issue, but I get easily  confused, must be my age!!!

![image](https://user-images.githubusercontent.com/30005040/53230029-9f200b00-367d-11e9-9a51-c9e3323b71b8.png)

**Comment by PromGames** [comment]
Yes , I know it, my bad, I will be more carefull next time.

**Comment by alpha117** [comment]
no problems
