### ISSUE TITLE
Insert WayPoint  offset to far from Insertion Point

### ISSUE THREAD

**Issue by alpha117** [CourseplayPathEditor/CoursePlay-Editor-6#9]
Would it be possible to reduce this?

![image](https://user-images.githubusercontent.com/30005040/53258668-25ac0b00-36c5-11e9-9d58-f63648e15949.png)

**Comment by TinyCrocodile** [comment]
Fixed in coursedrawer need to copy over

**Comment by alpha117** [comment]
great work...thanks

**Comment by PromGames** [comment]
@alpha117  @sootysax  

Check in version 21 in drive if we improve the routine to close this issue

**Comment by alpha117** [comment]
Perfect.....add Course Icon has changed?
![image](https://user-images.githubusercontent.com/30005040/53403224-2685bb00-39ab-11e9-9005-6cd7ea93b54d.png)

**Comment by alpha117** [comment]
closed
